// <auto-generated />
using CrudLocacao.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CrudLocacao.Migrations
{
    [DbContext(typeof(APIDbContext))]
    [Migration("20221020115404_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("CrudLocacao.Models.Imoveis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cep")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Imoveis");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cep = "39745180",
                            Name = "casaMG"
                        },
                        new
                        {
                            Id = 2,
                            Cep = "13745180",
                            Name = "casaGO"
                        },
                        new
                        {
                            Id = 3,
                            Cep = "12745180",
                            Name = "casaSP"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
